config/routes.rb
Rails.application.routes.draw do
  root 'vehicles#index'
  resources :vehicles, only: %i[show index destroy]
  resources :vehicle_types, except: %i[destroy]
  resources :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_type
  belongs_to :customer

  scope :sorted, ->(by) { eager_load(:vehicle_type, :customer).order(lower(by)) }

  validates :length_in_feet, numericality: true

  delegate :name, to: :vehicle_type, prefix: true, allow_nil: true
  delegate :full_name, to: :customer, prefix: true, allow_nil: true

  class << self
    def lower(query)
      # I hate doing this, in production I'd solve this, but time to submit this
      # exercise already!
      query == "length_in_feet" ? query : Arel.sql("LOWER(#{query})")
    end
  end
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
  has_many :vehicles

  validates :name, presence: true, uniqueness: true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.sorted(sort_by).all
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :length_in_feet, :vehicle_type_id, :customer_id)
    end

    def sort_by
      PERMITTED_SORT_VALUES.include?(params[:sort_by]) ? params[:sort_by] : "vehicles.name"
    end

    PERMITTED_SORT_VALUES = %w[vehicles.name length_in_feet vehicle_types.name customers.last_name]
end

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Vehicle Name', vehicles_path(sort_by: 'vehicles.name') %></th>
      <th><%= link_to 'Length', vehicles_path(sort_by: 'length_in_feet') %> (in feet)</th>
      <th><%= link_to 'Vehicle type', vehicles_path(sort_by: 'vehicle_types.name') %></th>
      <th><%= link_to 'Customer', vehicles_path(sort_by: 'customers.last_name') %></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= link_to vehicle.name, vehicle %></td>
        <td><%= vehicle.length_in_feet %></td>
        <td><%= vehicle.vehicle_type_name %></td>
        <td><%= vehicle.customer_full_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle.name %>
</p>

<p>
  <strong>Length:</strong>
  <%= @vehicle.length_in_feet %> feet
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @vehicle.vehicle_type_name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @vehicle.customer_full_name %>
</p>

<%= link_to 'Destroy', @vehicle, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', vehicles_path %>